version: '3'

services:
  elkarbackup:
    build: ./apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password"
      EB_CRON: "enabled"
    volumes:
      - "/path/to/backup/directory:/app/backups"
      - "/path/to/uploads/directory:/app/uploads"
      - "/path/to/sshkeys/directory:/app/.ssh"
    ports:
     - 8000:80

  db:
    image: hypriot/rpi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "your-password"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"

  client:
    build: ./client
